#!/usr/bin/env python3
"""
Build the customer-facing pricing calculator from the internal sales one.

Source (edit this one):  public/preview/licensing-calculator.html   (sales)
Output (never edit):     public/preview/pricing-calculator.html     (customer)

Everything between INTERNAL-START/INTERNAL-END markers (HTML comments or JS
block comments) is removed, CUSTOMER-START/CUSTOMER-END blocks are uncommented,
and CUSTOMER_MODE is switched on. Removing the content, rather than hiding it,
matters: anything left in the page can be read with "view source".

The script refuses to write the output if any known internal-only phrase
survives. It also refreshes the local working copy in /opt/www/xgrc-licensing.

Usage: python3 scripts/build-pricing-calculator.py
"""
import os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'public', 'preview', 'licensing-calculator.html')
OUT = os.path.join(ROOT, 'public', 'preview', 'pricing-calculator.html')
WORKING_COPY = '/opt/www/xgrc-licensing/quote-calculator.html'

# Phrases that must never reach the customer page.
FORBIDDEN = [
    'SALES PREVIEW', 'price book', 'placeholders pending', 'legacy', 'Legacy',
    'MSX', 'Quick Start', 'SEAT_PRESETS = {\n', 'DISCOUNT_THRESHOLDS = {',
    'Volume discount', 'compounding', 'Provisioning is manual', 'INTERNAL',
    'ZAR: 1500', 'ZAR: 550', 'converted from USD',
]

src = open(SRC, encoding='utf-8').read()
out = src

out = re.sub(r'<!--INTERNAL-START-->.*?<!--INTERNAL-END-->', '', out, flags=re.S)
out = re.sub(r'<!--CUSTOMER-START (.*?) CUSTOMER-END-->', r'\1', out, flags=re.S)
out = re.sub(r'/\*INTERNAL-START\*/.*?/\*INTERNAL-END\*/', '', out, flags=re.S)
out = re.sub(r'/\*CUSTOMER-START (.*?) CUSTOMER-END\*/', r'\1', out, flags=re.S)
out = out.replace('/*MODE*/false', 'true')
out = out.replace('<!--MODE:sales-->', '<!--MODE:customer (generated by scripts/build-pricing-calculator.py, do not edit)-->')
out = out.replace('<title>XGRC® Licensing Quote Calculator</title>', '<title>XGRC® Pricing Calculator</title>')
out = re.sub(r'\n[ \t]*\n(?:[ \t]*\n)+', '\n\n', out)

leaks = [p for p in FORBIDDEN if p in out]
if 'CUSTOMER-START' in out or 'CUSTOMER-END' in out:
    leaks.append('unbalanced CUSTOMER marker')
if 'const CUSTOMER_MODE = true;' not in out:
    leaks.append('CUSTOMER_MODE flag not switched on')
if '<meta name="robots" content="noindex, nofollow, noarchive">' not in out:
    leaks.append('noindex meta missing')
if leaks:
    sys.exit('Refusing to write customer calculator, found: ' + ', '.join(leaks))

open(OUT, 'w', encoding='utf-8').write(out)
print(f'Wrote {os.path.relpath(OUT, ROOT)} ({len(out):,} bytes, sales source {len(src):,} bytes)')

# Local working copy mirrors the sales page, minus the noindex tag (as before).
if os.path.isdir(os.path.dirname(WORKING_COPY)):
    open(WORKING_COPY, 'w', encoding='utf-8').write(
        src.replace('<meta name="robots" content="noindex, nofollow, noarchive">\n', ''))
    print(f'Refreshed working copy {WORKING_COPY}')
